requires 'Email::Stuffer';
requires 'IO::Async';
requires 'IO::Async::Loop::Mojo';
requires 'Log::Any::Adapter::MojoLog';
requires 'Mojolicious';
requires 'Mojolicious::Plugin::OpenTelemetry';
requires 'OpenTelemetry', '0.019';
requires 'OpenTelemetry::Exporter::OTLP';
requires 'OpenTelemetry::SDK';

# Optional dependencies, for additional features
requires 'Compress::Zlib';
requires 'Google::ProtocolBuffers::Dynamic';

# Only for testing
requires 'Mojo::SQLite';
