#!/usr/bin/env perl

# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

use Mojolicious::Lite -signatures;

use Metrics::Any::Adapter 'Stderr';
use Log::Any::Adapter 'OpenTelemetry';
use OpenTelemetry;
use OpenTelemetry::SDK;
use OpenTelemetry::Constants -span;
use Syntax::Keyword::Dynamically;
use OpenTelemetry::Integration qw( DBI HTTP::Tiny );
use Email::Stuffer;
use Mojo::SQLite;
use HTTP::Tiny;

use experimental qw( isa try );
use lib 'lib';

plugin 'OpenTelemetry';

helper sql => sub { state $sql = Mojo::SQLite->new; $sql };

app->sql->migrations->name('test')->from_string(<<'EOF')->migrate;
-- 1 up
create table known_emails (id integer primary key autoincrement, email text);
-- 1 down
drop table known_emails;
EOF

post '/send_order_confirmation' => sub ($c) {
  my $data = $c->req->json;

  # Get the current auto-instrumented span
  my $span = OpenTelemetry::Trace
        ->span_from_context
        ->set_attribute( 'app.order.id' => $data->{order}{order_id} );

  my $body = $c->render_to_string(
    template => 'confirmation',
    order    => $data->{order} ,
  );

  $span->add_event( name => 'template rendered' );

  send_email(
    to        => $data->{email},
    html_body => $body,
  );

  my $res = HTTP::Tiny->new->get('http://httpbin/anything');
  app->log->debug('Call was ' . $res->{status});

  $c->rendered(200);
};

sub send_email (%args) {
  my $data = {
    from      => 'noreply@example.com',
    subject   => 'Your confirmation email',
    transport => 'Test',
    %args,
  };

  # Create and start a manual span
  my $tracer = OpenTelemetry->tracer_provider->tracer( name => 'emailservice' );

  $tracer->in_span( send_email => sub ($span, $context) {
    Email::Stuffer->new($data)->send;

    $span
        ->add_event( name => 'email sent' )
        ->set_attribute( 'app.email.recipient' => $data->{to} );

    app->log->info("Order confirmation email sent to: $data->{to}");

    my $seen = app->sql->db
      ->select( known_emails => ['id'] => { email => $data->{to} } )
      ->arrays
      ->size;

    if ($seen) {
        app->log->trace("$data->{to} is a known email");
    }
    else {
        app->log->warn("$data->{to} is a new email");
        app->sql->db
          ->insert( known_emails => { email => $data->{to} } )
          ->last_insert_id;
    }
  });

  # Manually created spans need to be ended
  # In Perl, the method `in_span` ends them automatically
  # Check out the OpenTelemetry Perl docs at:
  # https://metacpan.org/dist/OpenTelemetry/view/lib/OpenTelemetry/Trace/Tracer.pod#create_span
}

app->start;
